name: Mark stale issues and pull requests and cancel empty PRs

on:
  schedule:
    - cron: '21 21 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'Stale issue message'
          stale-pr-message: 'Stale pull request message'
          stale-issue-label: 'no-issue-activity'
          stale-pr-label: 'no-pr-activity'
  
  cancel-empty-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Cancel PRs without proper description
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Fetch all open pull requests in the repository.
            const prs = await github.paginate(github.rest.pulls.list, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open"
            });
            
            // Check for no open PRs.
            if (!prs || prs.length === 0) {
              console.log("No open pull requests found.");
              return;
            }
            
            for (const pr of prs) {
              // If the pull request description is empty or contains only whitespace,
              // consider it as lacking proper details.
              if (!pr.body || pr.body.trim().length === 0) {
                const username = pr.user && pr.user.login ? pr.user.login : "unknown user";
                console.log(`PR #${pr.number} by ${username} has an empty description.`);
                
                // Post a comment to inform the user if user information exists.
                if (pr.user && pr.user.login) {
                  await github.rest.issues.createComment({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: pr.number,
                    body: `@${pr.user.login}, your pull request has been closed because it does not include a description explaining the purpose of the PR. Please update your PR with the necessary details and reopen it.`
                  });
                } else {
                  console.log(`PR #${pr.number} has no valid user information, skipping comment.`);
                }
                
                // Close the pull request.
                await github.rest.pulls.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr.number,
                  state: "closed"
                });
                
                console.log(`PR #${pr.number} closed.`);
              }
            }
